name = "v1_8bit"
description = "Implementation of isapa128av20 and asconhashv12 with W=8 and CCW=8"

[language]
vhdl.standard = "2008"
vhdl.synopsys = false

[rtl]

sources = [
	"src_rtl/v1_8bit/design_pkg.vhd",
	"src_rtl/LWC_config_8.vhd",
	"src_rtl/LWC/NIST_LWAPI_pkg.vhd",
	"src_rtl/v1_8bit/CryptoCore.vhd",
	"src_rtl/LWC/key_piso.vhd",
	"src_rtl/LWC/FIFO.vhd",
	"src_rtl/LWC/data_sipo.vhd",
	"src_rtl/LWC/data_piso.vhd",
	"src_rtl/LWC/PreProcessor.vhd",
	"src_rtl/LWC/PostProcessor.vhd",
	"src_rtl/LWC/LWC_2pass.vhd"
]
top = 'LWC_2pass'
clock.port = "clk"

[tb]
top = 'LWC_TB'
sources = [
	"src_tb/v1_8bit/LWC_config_tb.vhd",
	"src_tb/LWC_TB_2pass_uut.vhd",
	"src_tb/LWC_TB.vhd"
]

[tb.generics]
G_FNAME_PDI.file = "KAT/v1_8bit/pdi.txt"
G_FNAME_SDI.file = "KAT/v1_8bit/sdi.txt"
G_FNAME_DO.file = "KAT/v1_8bit/do.txt"

[lwc]
aead.algorithm = "isapa128av20"
hash.algorithm = "asconhashv12"

ports.pdi.bit_width = 8
ports.sdi.bit_width = 8
