name = "v2"
description = "Implementation of isapk128av20 with W=16 and CCW=16"

[language]
vhdl.standard = "2008"
vhdl.synopsys = false

[rtl]

sources = [
	"src_rtl/v2/design_pkg.vhd",
	"src_rtl/LWC_config_16.vhd",
	"src_rtl/LWC/NIST_LWAPI_pkg.vhd",
	"src_rtl/v2/CryptoCore.vhd",
	"src_rtl/LWC/key_piso.vhd",
	"src_rtl/LWC/FIFO.vhd",
	"src_rtl/LWC/data_sipo.vhd",
	"src_rtl/LWC/data_piso.vhd",
	"src_rtl/LWC/PreProcessor.vhd",
	"src_rtl/LWC/PostProcessor.vhd",
	"src_rtl/LWC/LWC_2pass.vhd"
]
top = 'LWC_2pass'
clock.port = "clk"

[tb]
top = 'LWC_TB'
sources = [
	"src_tb/v2/LWC_config_tb.vhd",
	"src_tb/LWC_TB_2pass_uut.vhd",
	"src_tb/LWC_TB.vhd"
]

[tb.generics]
G_FNAME_PDI.file = "KAT/v2/pdi.txt"
G_FNAME_SDI.file = "KAT/v2/sdi.txt"
G_FNAME_DO.file = "KAT/v2/do.txt"

[lwc]
aead.algorithm = "isapk128av20"

ports.pdi.bit_width = 16
ports.sdi.bit_width = 16
